name: audiophile
services:
  frontend:
    build: ./frontend
    ports: [ "5173:80" ]
    depends_on:
      backend:
        condition: service_started
  backend:
    build: ./backend
    ports: ["5174:3000"]
    hostname: audiophile-backend
    volumes:
      - ./tmp:/app/storage
    depends_on:
      redis:
        condition: service_started
  redis:
    hostname: audiophile-redis
    image: "redis:alpine"
    ports: ["5175:6379"]
